import {
  warehouseMaterialsURL,
  seaManagementProductsURL,
  warehouseProductsURL,
  warehouseInvoiceVatURL,
  warehouseSemiProductsURL,
  warehousePurchaseBooksURL,
  warehouseSalesBooksURL,
  warehouseClosingMaterialsURL,
  warehouseClosingSemiProductsURL,
  warehouseClosingProductsURL,
  seaManagementMaterialsURL,
  seaManagementInvoiceImportURL,
  seaManagementInvoiceExportURL,
  standardNormsURL,
  standardProductsNormURL,
  standardSemiProductsNormURL,
  convertMaterialsURL,
  convertProductsURL,
  unitConversionURL,
  unitsURL,
  applyUsersURL,
  applyExportURL,
  applyVatURL,
  applyPurchaseURL,
  applySalesURL,
  applyProductNormURL,
  applyInventoryMaterialURL,
  applyInventoryProductURL,
  applyInventoryFromSemiProductURL,
  factorsUsersURL,
  factorsMaterialTempExportURL,
  factorsMaterialReexportURL,
  factorsMaterialReimportURL,
  factorsMaterialDisposeURL,
  factorsProductTempImportURL,
  factorsProductReimportURL,
  factorsProductReexportURL,
  factorsProductDisposeURL,
  factorsProductDestroyURL,
  prepareSettlementReportUserURL,
  prepareSettlementReportInventoryProductURL,
  prepareSettlementReportInventorySummaryURL,
  manageCatalogUserURL,
  manageCatalogRoleURL,
} from "../../routes/urls";
import type { SidebarData } from "./types";
import { FiBox, FiGrid, FiFileText, FiHome } from "react-icons/fi";

export const sidebarData: SidebarData = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: <FiHome />,
    path: "/",
  },
  {
    id: "data-sea-management",
    label: "Quản lý dữ liệu hải quan",
    icon: <FiBox />,
    children: [
      // {
      //   id: "materials",
      //   label: "Danh mục nguyên vật liệu",
      //   path: seaManagementMaterialsURL,
      //   icon: <FiGrid />,
      // },
      // {
      //   id: "product",
      //   label: "Danh mục sản phẩm",
      //   path: seaManagementProductsURL,
      //   icon: <FiFileText />,
      // },
      {
        id: "invoice-import",
        label: "Quản lý tờ khai nhập",
        path: seaManagementInvoiceImportURL,
        icon: <FiFileText />,
      },
      {
        id: "invoice-export",
        label: "Quản lý tờ khai xuất",
        path: seaManagementInvoiceExportURL,
        icon: <FiFileText />,
      },
    ],
  },
  {
    id: "warehouse-accounting-data",
    label: "Dữ liệu Kho và Kế toán",
    icon: <FiBox />,
    children: [
      {
        id: "materials-warehouse",
        label: "Danh mục nguyên vật liệu",
        path: warehouseMaterialsURL,
        icon: <FiGrid />,
      },
      {
        id: "product-warehouse",
        label: "Danh mục sản phẩm",
        path: warehouseProductsURL,
        icon: <FiFileText />,
      },
      // {
      //   id: "invoice-vat-warehouse",
      //   label: "Quản lý hóa đơn điện tử (VAT)",
      //   path: warehouseInvoiceVatURL,
      //   icon: <FiFileText />,
      // },
      // {
      //   id: "semi-product-warehouse",
      //   label: "Danh mục bán thành phẩm",
      //   path: warehouseSemiProductsURL,
      //   icon: <FiFileText />,
      // },
      // {
      //   id: "purchase-book-warehouse",
      //   label: "Quản lý sổ mua hàng",
      //   path: warehousePurchaseBooksURL,
      //   icon: <FiFileText />,
      // },
      // {
      //   id: "sales-book-warehouse",
      //   label: "Quản lý sổ bán hàng",
      //   path: warehouseSalesBooksURL,
      //   icon: <FiFileText />,
      // },
      {
        id: "closing-material-warehouse",
        label: "Quản lý chốt tồn kho nguyên vật liệu",
        path: warehouseClosingMaterialsURL,
        icon: <FiFileText />,
      },
      // {
      //   id: "closing-semi-product-warehouse",
      //   label: "Quản lý chốt tồn kho bán thành phẩm",
      //   path: warehouseClosingSemiProductsURL,
      //   icon: <FiFileText />,
      // },
      {
        id: "closing-product-warehouse",
        label: "Quản lý chốt tồn kho sản phẩm",
        path: warehouseClosingProductsURL,
        icon: <FiFileText />,
      },
    ],
  },
  {
    id: "standard-management",
    label: "Quản lý định mức",
    icon: <FiBox />,
    children: [
      {
        id: "norm",
        label: "Danh mục định mức",
        path: standardNormsURL,
        icon: <FiGrid />,
      },
      {
        id: "norm-product",
        label: "Định mức sản phẩm",
        path: standardProductsNormURL,
        icon: <FiFileText />,
      },
      {
        id: "norm-semi-product",
        label: "Định mức bán thành phẩm",
        path: standardSemiProductsNormURL,
        icon: <FiFileText />,
      },
    ],
  },
  {
    id: "data-conversion",
    label: "Chuyển đổi dữ liệu",
    icon: <FiBox />,
    children: [
      // {
      //   id: "convert-material",
      //   label: "Chuyển đổi mã NVL(Nội bộ - Hải quan)",
      //   path: convertMaterialsURL,
      //   icon: <FiGrid />,
      // },
      // {
      //   id: "convert-product",
      //   label: "Chuyển đổi mã SP(Nội bộ - Hải quan)",
      //   path: convertProductsURL,
      //   icon: <FiFileText />,
      // },
      {
        id: "unit-conversion",
        label: "Bảng quy đổi đơn vị tính",
        path: unitConversionURL,
        icon: <FiFileText />,
      },
      {
        id: "norm-management",
        label: "Quản lý đơn vị tính",
        path: unitsURL,
        icon: <FiFileText />,
      },
    ],
  },
  {
    id: "apply-data",
    label: "Áp dữ liệu vào năm tài chính",
    icon: <FiFileText />,
    children: [
      {
        id: "user",
        label: "Áp dữ liệu tờ khai nhập",
        path: applyUsersURL,
        icon: <FiFileText />,
      },
      {
        id: "apply-export",
        label: "Áp dữ liệu tờ khai xuất",
        path: applyExportURL,
        icon: <FiFileText />,
      },
      // {
      //   id: "apply-vat",
      //   label: "Áp dữ liệu hóa đơn VAT",
      //   path: applyVatURL,
      //   icon: <FiFileText />,
      // },
      // {
      //   id: "apply-purchase",
      //   label: "Áp dữ liệu sổ mua hàng",
      //   path: applyPurchaseURL,
      //   icon: <FiFileText />,
      // },
      // {
      //   id: "apply-sales",
      //   label: "Áp dữ liệu sổ bán hàng",
      //   path: applySalesURL,
      //   icon: <FiFileText />,
      // },
      {
        id: "apply-product-norm",
        label: "Áp định mức sản phẩm",
        path: applyProductNormURL,
        icon: <FiFileText />,
      },
      // {
      //   id: "inventory-material",
      //   label: "Tổng hợp tồn kho nvl/sổ kế toán 152",
      //   path: applyInventoryMaterialURL,
      //   icon: <FiFileText />,
      // },
      // {
      //   id: "inventory-product",
      //   label: "Tổng hợp tồn kho sp/sổ kế toán 155",
      //   path: applyInventoryProductURL,
      //   icon: <FiFileText />,
      // },
      // {
      //   id: "inventory-from-semi-product",
      //   label: "Tổng hợp tồn nvl từ bán thành phẩm",
      //   path: applyInventoryFromSemiProductURL,
      //   icon: <FiFileText />,
      // },
    ],
  },
  // {
  //   id: "factors-affecting-existence",
  //   label: "Các yếu tố ảnh hưởng tồn",
  //   icon: <FiFileText />,
  //   children: [
  //     {
  //       id: "user",
  //       label: "Quản lý nguyên vật liệu tiêu hủy ngoài định mức",
  //       path: factorsUsersURL,
  //       icon: <FiFileText />,
  //     },
  //     {
  //       id: "material-temp-export",
  //       label: "Quản lý nguyên vật liệu tạm xuất",
  //       path: factorsMaterialTempExportURL,
  //       icon: <FiFileText />,
  //     },
  //     {
  //       id: "material-reexport",
  //       label: "Quản lý nguyên vật liệu tái xuất",
  //       path: factorsMaterialReexportURL,
  //       icon: <FiFileText />,
  //     },
  //     {
  //       id: "material-reimport",
  //       label: "Quản lý nguyên vật liệu tái nhập",
  //       path: factorsMaterialReimportURL,
  //       icon: <FiFileText />,
  //     },
  //     {
  //       id: "material-dispose",
  //       label: "Quản lý nguyên vật liệu CĐMĐSD, thiêu thụ nội địa, thanh lý",
  //       path: factorsMaterialDisposeURL,
  //       icon: <FiFileText />,
  //     },
  //     {
  //       id: "product-temp-import",
  //       label: "Quản lý sản phẩm tạm nhập",
  //       path: factorsProductTempImportURL,
  //       icon: <FiFileText />,
  //     },
  //     {
  //       id: "product-reimport",
  //       label: "Quản lý sản phẩm tái nhập",
  //       path: factorsProductReimportURL,
  //       icon: <FiFileText />,
  //     },
  //     {
  //       id: "product-reexport",
  //       label: "Quản lý sản phẩm tái xuất",
  //       path: factorsProductReexportURL,
  //       icon: <FiFileText />,
  //     },
  //     {
  //       id: "product-dispose",
  //       label: "Quản lý sản phẩm CĐMĐSD, thiêu thụ nội địa, thanh lý",
  //       path: factorsProductDisposeURL,
  //       icon: <FiFileText />,
  //     },
  //     {
  //       id: "product-destroy",
  //       label: "Quản lý sản phẩm tiêu hủy ngoài định mức",
  //       path: factorsProductDestroyURL,
  //       icon: <FiFileText />,
  //     },
  //   ],
  // },
  {
    id: "prepare-settlement-report",
    label: "Lập báo cáo quyết toán",
    icon: <FiFileText />,
    children: [
      {
        id: "user",
        label: "Báo cáo quyết toán tồn nguyên vật liệu",
        path: prepareSettlementReportUserURL,
        icon: <FiFileText />,
      },
      {
        id: "inventory-report-product",
        label: "Báo cáo quyết toán tồn sản phẩm",
        path: prepareSettlementReportInventoryProductURL,
        icon: <FiFileText />,
      },
      {
        id: "inventory-report-summary",
        label: "Tổng hợp tồn nguyên vật liệu",
        path: prepareSettlementReportInventorySummaryURL,
        icon: <FiFileText />,
      },
    ],
  },
  // {
  //   id: "manage-catalog",
  //   label: "Quản lý danh mục",
  //   icon: <FiFileText />,
  //   children: [
  //     {
  //       id: "user",
  //       label: "Quản lý hợp đồng gia công",
  //       path: manageCatalogUserURL,
  //       icon: <FiFileText />,
  //     },
  //     {
  //       id: "roles",
  //       label: "Quản lý danh mục sản phẩm",
  //       path: manageCatalogRoleURL,
  //       icon: <FiFileText />,
  //     },
  //   ],
  // },
];
