"""remove unique binding

Revision ID: 06b457e2a0d4
Revises: 49572abcfb33
Create Date: 2025-12-23 18:09:11.143124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b457e2a0d4'
down_revision: Union[str, Sequence[str], None] = '49572abcfb33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('export_declarations_importer_key'), 'export_declarations', type_='unique')
    op.drop_constraint(op.f('import_declarations_exporter_key'), 'import_declarations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('import_declarations_exporter_key'), 'import_declarations', ['exporter'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('export_declarations_importer_key'), 'export_declarations', ['importer'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
