"""initial database

Revision ID: 49572abcfb33
Revises: 
Create Date: 2025-11-09 00:20:26.310615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49572abcfb33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('currency_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('norms',
    sa.Column('norm_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('store_code', sa.String(length=50), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('unit_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('representative', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('convert_units',
    sa.Column('source_unit', sa.Uuid(), nullable=False),
    sa.Column('target_unit', sa.Uuid(), nullable=False),
    sa.Column('conversion', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_unit'], ['units.id'], ),
    sa.ForeignKeyConstraint(['target_unit'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=500), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('partner_code', sa.String(length=10), nullable=False),
    sa.Column('partner_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('partner_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id_2', sa.Uuid(), nullable=False),
    sa.Column('norm_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_semi_product', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['norm_id'], ['norms.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['unit_id_2'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compare_material_codes',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('internal_code', sa.String(length=50), nullable=True),
    sa.Column('external_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compare_product_codes',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('internal_code', sa.String(length=50), nullable=True),
    sa.Column('external_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('licence_number', sa.String(length=50), nullable=True),
    sa.Column('licence_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_licence_date', sa.DateTime(), nullable=True),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_declarations',
    sa.Column('export_declaration_number', sa.String(length=50), nullable=False),
    sa.Column('licence_number', sa.String(length=50), nullable=True),
    sa.Column('licence_date', sa.DateTime(), nullable=True),
    sa.Column('bill_number', sa.String(length=50), nullable=True),
    sa.Column('importer', sa.String(length=500), nullable=False),
    sa.Column('importer_id', sa.Uuid(), nullable=False),
    sa.Column('usd_exchange_rate', sa.Float(), nullable=True),
    sa.Column('currency_id', sa.Uuid(), nullable=True),
    sa.Column('type_declaration', sa.String(length=100), nullable=False),
    sa.Column('type_inventory', sa.String(length=100), nullable=False),
    sa.Column('shipping_term', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['importer_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('importer')
    )
    op.create_table('import_declarations',
    sa.Column('import_declaration_number', sa.String(length=50), nullable=False),
    sa.Column('licence_number', sa.String(length=50), nullable=True),
    sa.Column('licence_date', sa.DateTime(), nullable=True),
    sa.Column('bill_number', sa.String(length=50), nullable=True),
    sa.Column('exporter', sa.String(length=500), nullable=False),
    sa.Column('exporter_id', sa.Uuid(), nullable=False),
    sa.Column('usd_exchange_rate', sa.Float(), nullable=True),
    sa.Column('currency_id', sa.Uuid(), nullable=True),
    sa.Column('type_declaration', sa.String(length=100), nullable=False),
    sa.Column('type_inventory', sa.String(length=100), nullable=False),
    sa.Column('shipping_term', sa.String(length=50), nullable=True),
    sa.Column('shipping_fee', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['exporter_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exporter')
    )
    op.create_table('invoices',
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('invoice_type', sa.String(length=50), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('usd_exchange_rate', sa.Float(), nullable=True),
    sa.Column('vat_license_number', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_destructions',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id_2', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity_2', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('destruction_date', sa.DateTime(), nullable=False),
    sa.Column('licence_number', sa.String(length=50), nullable=True),
    sa.Column('licence_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['unit_id_2'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_stores',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('norm_details',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('norm_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('norm_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['norm_id'], ['norms.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_liquidations',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('liquidation_date', sa.DateTime(), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=True),
    sa.Column('quantity_on_hand_2', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('licence_number', sa.String(length=50), nullable=True),
    sa.Column('licence_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_stores',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=True),
    sa.Column('quantity_on_hand_2', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_declaration_details',
    sa.Column('hs_code', sa.String(length=50), nullable=False),
    sa.Column('export_declaration_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('origin_country_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id_2', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity2', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('unit_price_transport', sa.Float(), nullable=True),
    sa.Column('invoice_value', sa.Float(), nullable=True),
    sa.Column('taxable_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['export_declaration_id'], ['export_declarations.id'], ),
    sa.ForeignKeyConstraint(['origin_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['unit_id_2'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_declaration_details',
    sa.Column('hs_code', sa.String(length=50), nullable=False),
    sa.Column('import_declaration_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('origin_country_id', sa.Uuid(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit2', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity2', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('unit_price_transport', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['import_declaration_id'], ['import_declarations.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['origin_country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices_details',
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('material_name', sa.String(length=500), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id_2', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity_2', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['unit_id_2'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_receive_details',
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=500), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('accounting_date', sa.DateTime(), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('licence_date', sa.DateTime(), nullable=True),
    sa.Column('licence_number', sa.String(length=50), nullable=False),
    sa.Column('import_declaration_id', sa.Uuid(), nullable=False),
    sa.Column('import_declaration_number', sa.String(length=50), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('debit_account', sa.String(length=50), nullable=True),
    sa.Column('credit_account', sa.String(length=50), nullable=True),
    sa.Column('vat_value', sa.Float(), nullable=True),
    sa.Column('import_tax_value', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('transport_value', sa.Float(), nullable=True),
    sa.Column('storee_fee', sa.Float(), nullable=True),
    sa.Column('customs_fee', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id_2', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity_2', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['import_declaration_id'], ['import_declarations.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['unit_id_2'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_semi_products',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_end', sa.Float(), nullable=True),
    sa.Column('quantity_end_2', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('checked_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_sell_details',
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('accounting_date', sa.DateTime(), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('export_declaration_id', sa.Uuid(), nullable=False),
    sa.Column('export_declaration_number', sa.String(length=50), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('debit_account', sa.String(length=50), nullable=True),
    sa.Column('credit_account', sa.String(length=50), nullable=True),
    sa.Column('vat_value', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('transport_value', sa.Float(), nullable=True),
    sa.Column('storee_fee', sa.Float(), nullable=True),
    sa.Column('customs_fee', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id_2', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity_2', sa.Float(), nullable=True),
    sa.Column('sales_revenue', sa.Float(), nullable=True),
    sa.Column('sales_revenue_2', sa.Float(), nullable=True),
    sa.Column('return_quantity', sa.Float(), nullable=True),
    sa.Column('return_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['export_declaration_id'], ['export_declarations.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['unit_id_2'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convert_semi_products',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('semi_product_id', sa.Uuid(), nullable=False),
    sa.Column('conversion', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['semi_product_id'], ['material_semi_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convert_semi_products')
    op.drop_table('product_sell_details')
    op.drop_table('material_semi_products')
    op.drop_table('material_receive_details')
    op.drop_table('invoices_details')
    op.drop_table('import_declaration_details')
    op.drop_table('export_declaration_details')
    op.drop_table('product_stores')
    op.drop_table('product_liquidations')
    op.drop_table('norm_details')
    op.drop_table('material_stores')
    op.drop_table('material_destructions')
    op.drop_table('invoices')
    op.drop_table('import_declarations')
    op.drop_table('export_declarations')
    op.drop_table('contracts')
    op.drop_table('compare_product_codes')
    op.drop_table('compare_material_codes')
    op.drop_table('products')
    op.drop_table('partners')
    op.drop_table('materials')
    op.drop_table('convert_units')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('stores')
    op.drop_table('norms')
    op.drop_table('currencies')
    op.drop_table('countries')
    # ### end Alembic commands ###
