"""changes style in status on users table

Revision ID: 52fe51b3d2f3
Revises: 49572abcfb33
Create Date: 2025-11-24 13:33:30.975797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fe51b3d2f3'
down_revision: Union[str, Sequence[str], None] = '49572abcfb33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'unit_id_2',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'unit_id_2',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
