"""update import declaration details

Revision ID: eb4aa1a6de30
Revises: 06b457e2a0d4
Create Date: 2025-12-26 09:42:46.093659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4aa1a6de30'
down_revision: Union[str, Sequence[str], None] = '06b457e2a0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_declaration_details', sa.Column('unit_id', sa.Uuid(), nullable=True))
    op.add_column('import_declaration_details', sa.Column('unit_id_2', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'import_declaration_details', 'units', ['unit_id_2'], ['id'])
    op.create_foreign_key(None, 'import_declaration_details', 'units', ['unit_id'], ['id'])
    op.drop_column('import_declaration_details', 'unit')
    op.drop_column('import_declaration_details', 'unit2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_declaration_details', sa.Column('unit2', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('import_declaration_details', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'import_declaration_details', type_='foreignkey')
    op.drop_constraint(None, 'import_declaration_details', type_='foreignkey')
    op.drop_column('import_declaration_details', 'unit_id_2')
    op.drop_column('import_declaration_details', 'unit_id')
    # ### end Alembic commands ###
